### ISSUE TITLE
Write ‘Find’ as a type synonym

### ISSUE THREAD

**Issue by Icelandjack** [sweirich/dth#6]
I'm curious if a type synonym is equivalent to [`Find`](https://github.com/sweirich/dth/blob/master/popl17/src/RegexpDependent.hs#L153 )

```haskell
-- type family 
--   Find (n :: Symbol) (s :: SM) :: Index n o s where
--   Find n s = FindH n s s

type Find n s = (FindH n s s :: Index n o s) 
```

and if there are any differences

**Comment by sweirich** [comment]
Yes, it works. I don't think it makes a difference either way.

**Comment by Icelandjack** [comment]
Okay just curious :)

**Comment by sweirich** [comment]
Good question though.  Do you find type synonyms easier to read than type families?

**Comment by Icelandjack** [comment]
Type synonyms are not very powerful compared to type families (when I see one I know there is no funny business like recursion going on), plus they are shorter (I'll assume [`#11622`](https://ghc.haskell.org/trac/ghc/ticket/11622) is implemented) 

```haskell
type Find n s = FindH n s s :: Index n o s
```

so I can read them more quickly.
