### ISSUE TITLE
PerfectTree TF Implementation Bugs

### ISSUE THREAD

**Issue by dwincort** [sweirich/dth#8]
Hi Stephanie,

I just read your [blog post on nested data types](https://www.cis.upenn.edu/~plclub/blog/2020-12-04-nested-datatypes/), and I thought it was a lot of fun!  At the end, you link to a few alternative ways to define perfect trees, and I took a look at that code.  It seems this code hasn't been touched in over 6 years, but still, something in [singleton-tf](https://github.com/sweirich/dth/blob/master/examples/perfect-trees/singleton-tf.hs) caught my eye.  You define the type family:
```haskell
type family Perfect (t :: TreeShape) :: Bool where
    Perfect LeafShape       = True     
    Perfect (NodeShape l l) = True    -- require left and right to have same shape
    Perfect (NodeShape l r) = False
```
But, this isn't quite right.  Not only do you need the two branches to be equal, but you also need them to be perfect.  As it stands, the following bad tree is type checked as perfect:
```haskell
bad' = Node one' 2 zero'
bad = Tree $ Node bad' 3 bad'
```
You _could_ fix this by changing the result of the second case to `Perfect l`, but you still run into the same problems with `decr` and `merge` down below.  Another natural definition that works is:
```haskell
type family Perfect (t :: TreeShape) :: Constraint where
    Perfect LeafShape       = ()
    Perfect (NodeShape l r) = (l ~ r, Perfect l)

data PerfectTree (a :: *) = forall (t :: TreeShape). Perfect t => Tree (Tree t a)
```
Not only is it a little cleaner (just `Perfect t` as a constraint instead of `Perfect t ~ True`), but it naturally gives you the power you need to write `decr` and `merge`:
```haskell
decr :: PerfectTree a -> PerfectTree a
decr (Tree (Node (Node ll xl lr) xc (Node rl xr rr))) = Tree $ Node ll xc lr
decr (Tree Leaf) = Tree Leaf

merge :: forall a. Semigroup a => PerfectTree a -> PerfectTree a -> Maybe (PerfectTree a)
merge (Tree t1) (Tree t2) = Tree <$> go t1 t2
  where
    go :: (Perfect t1, Perfect t2) => Tree t1 a -> Tree t2 a -> Maybe (Tree t1 a)
    go Leaf Leaf = Just Leaf
    go (Node ll xl lr) (Node rl xr rr) = do
      l <- go ll rl
      r <- go lr rr
      pure $ Node l (xl <> xr) r
    go _ _ = Nothing
```

Anyway, thanks again for writing the blog post!

P.S. If you do go ahead and update this, you should probably also fix `height` so that it adds 1 in the recursive case.

**Comment by sweirich** [comment]
Thanks!  I've fixed this with 65ab37d.  This commit removes that file and replaces it with your updated version in ConstraintTF.hs.

You also reminded me that I had worked out a different version that uses type families, so I added that as well (see SingletonTF.lhs).
